# Generated by Django 4.0.4 on 2022-05-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lessons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
    ]
