# Generated by Django 4.0.4 on 2022-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.URLField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'article'), ('quiz', 'quiz'), ('video', 'Video')], default='article', max_length=20),
        ),
    ]
