# Generated by Django 4.0.4 on 2022-05-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_lesson_youtube_id_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
