# Generated by Django 4.0.4 on 2022-05-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_lesson_youtube_id_lesson_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'article'), ('quiz', 'quiz'), ('video', 'video')], default='article', max_length=20),
        ),
    ]
