# Generated by Django 4.0.4 on 2022-05-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
