# Generated by Django 4.0.4 on 2022-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_lesson_lesson_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_style',
            field=models.CharField(choices=[('problem', 'problem'), ('knowledge', 'knowledge foundation'), ('solution', 'solution'), ('task', 'task')], default='problem', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('article', 'article'), ('quiz', 'quiz'), ('video', 'video'), ('submission', 'submission')], default='article', max_length=20),
        ),
    ]
