# Generated by Django 4.0.4 on 2022-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_lesson_lesson_style_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_submission',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
