# Generated by Django 4.0.4 on 2022-05-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='student',
        ),
    ]
