# Generated by Django 4.0.4 on 2022-05-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0005_quest_quest_map_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='map_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
