# Generated by Django 4.0.4 on 2022-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_quest_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='name',
            field=models.CharField(blank=True, default='quest_name', max_length=50, null=True),
        ),
    ]
