# Generated by Django 4.0.4 on 2022-05-17 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quest', '0007_scene_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='accumulated_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quest.choice')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quest.scene')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
